/* This file is auto-generated by the ScriptDirectedGui program.                  */
/* Please do not modify directly as the code cannot then be guaranteed to operate */
/* correctly. However, please feel free to copy the source into a project.        */

package com.ptconsultancy.createdgui;

import static com.ptconsultancy.constants.ServiceAdminConstants.MAIN_HEADING;

import com.ptconsultancy.admin.adminsupport.BuildVersion;
import com.ptconsultancy.guicomponents.FreeButton;
import com.ptconsultancy.guicomponents.FreeLabel;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JPanel;

public class AboutDialog extends JFrame {

    private static final String TITLE = "About";
    private static final int FRAME_X_SIZE = 400;
    private static final int FRAME_Y_SIZE = 300;
    private Color col = new Color(230, 255, 255);

    private AboutDialog tg = this;

    private MainDialog mainDialog;

    public AboutDialog(MainDialog mainDialog) {
        this.mainDialog = mainDialog;
        this.mainDialog.setEnabled(false);
        this.setTitle(TITLE);
        this.setSize(FRAME_X_SIZE, FRAME_Y_SIZE);

        JPanel p1 = new JPanel();
        p1.setLayout(null);
        p1.setBackground(col);

        FreeLabel l0 = new FreeLabel(MAIN_HEADING, 30, 30, 500, 30, new Font("", Font.BOLD + Font.ITALIC, 20));

        FreeButton b0 = new FreeButton("OK", 160, 200, 80);

        FreeLabel comp0 = new FreeLabel("ServicesAdminManager", 30, 90, 200, 20);

        FreeLabel comp1 = new FreeLabel("Version " + BuildVersion.getBuildVersion(), 30, 140, 200, 20);

        // This is the control for the OK button
        b0.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                mainDialog.setEnabled(true);
                tg.dispose();
            }
        });

        p1.add(b0);
        p1.add(comp0);
        p1.add(comp1);
        p1.add(l0);
        this.add(p1);
    }
}
