/* This file is auto-generated by the ScriptDirectedGui program.                  */
/* Please do not modify directly as the code cannot then be guaranteed to operate */
/* correctly. However, please feel free to copy the source into a project.        */

package com.ptconsultancy.createdgui;

import com.ptconsultancy.admin.Admin;
import com.ptconsultancy.admin.Service;
import com.ptconsultancy.domain.guicomponents.FreeButton;
import com.ptconsultancy.domain.guicomponents.FreeLabel;
import com.ptconsultancy.domain.guicomponents.FreeLabelTextFieldPair;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.util.StringUtils;

public class BuildEndpointURLDialog extends JFrame {

    private static final String MAIN_HEADING = "Services Admin Manager";
    private static final String TITLE = "Build Endpoint URL";
    private static final int FRAME_X_SIZE = 800;
    private static final int FRAME_Y_SIZE = 500;
    private Color col = new Color(235, 255, 255);

    private static final int NUM_PARAMS = 4;

    private BuildEndpointURLDialog tg = this;

    private EndpointTestDialog endpointTestDialog;

    private String serviceName;

    private FreeButton[] freeUserButtons = new FreeButton[NUM_PARAMS];
    private FreeButton[] freePassButtons = new FreeButton[NUM_PARAMS];

    private Admin admin;

    @Autowired
    public BuildEndpointURLDialog(Admin admin, EndpointTestDialog ept, String serviceName) {

        this.admin = admin;

        endpointTestDialog = ept;
        endpointTestDialog.setEnabled(false);

        this.serviceName = serviceName;

        this.setTitle(TITLE);
        this.setSize(FRAME_X_SIZE, FRAME_Y_SIZE);

        JPanel p1 = new JPanel();
        p1.setLayout(null);
        p1.setBackground(col);

        final int xAndyStart = 30;
        final int xSize = 500;
        final int fontSize = 20;
        final String fontName = "";
        FreeLabel l0 = new FreeLabel(MAIN_HEADING, xAndyStart, xAndyStart, xSize, xAndyStart, new Font(fontName, Font.BOLD + Font.ITALIC, fontSize));

        int xpos = FRAME_X_SIZE / 2 - 190;
        int ypos = FRAME_Y_SIZE - 100;
        int buttonSize = 80;
        FreeButton b0 = new FreeButton("Test", xpos, ypos, buttonSize);

        xpos = xpos + 110;
        FreeButton b1 = new FreeButton("Set URL", xpos, ypos, buttonSize);

        xpos = xpos + 110;
        FreeButton b3 = new FreeButton(FreeButton.CLEAR, xpos, ypos, buttonSize);

        xpos = xpos + 110;
        FreeButton b2 = new FreeButton(FreeButton.CANCEL, xpos, ypos, buttonSize);

        FreeLabel comp0 = new FreeLabel("Building Enpoint URL for service: " + this.serviceName, 30, 90, 600, 20);

        FreeLabelTextFieldPair comp1 = new FreeLabelTextFieldPair(col, "Please enter endpoint name:", 30, 140, 240);

        FreeLabelTextFieldPair[] freeLabelTextFieldPairs = new FreeLabelTextFieldPair[NUM_PARAMS];
        for (int i = 0; i < NUM_PARAMS; i++) {
            freeLabelTextFieldPairs[i] = new FreeLabelTextFieldPair(col, "Parameter " + (i + 1) + ":", 30, 190 + (i * 50), 240);
            freeUserButtons[i] = new FreeButton("Use ID", 500, 190 + (i* 50), 120);
            freePassButtons[i] = new FreeButton("Use Pass", 650, 190 + (i* 50), 120);

            if (i > 0) {
                freeUserButtons[i].setVisible(false);
                freePassButtons[i].setVisible(false);
            }

            final int index = i;
            freeUserButtons[i].addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    Service service = admin.getServiceByName(serviceName);
                    freeLabelTextFieldPairs[index].setText(service.getCredentials().getUserId());
                    enableAllUserButtons(false);
                    manageUserPassButtons(index);
                }
            });

            freePassButtons[i].addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    Service service = admin.getServiceByName(serviceName);
                    freeLabelTextFieldPairs[index].setText(service.getCredentials().getPassword());
                    enableAllPassButtons(false);
                    manageUserPassButtons(index);
                }
            });

            freeLabelTextFieldPairs[i].getTextField().addActionListener(new ActionListener() {
                public void actionPerformed(ActionEvent e) {
                    if (freeLabelTextFieldPairs[index].getTextField().isFocusOwner()) {
                        manageUserPassButtons(index);
                    }
                }
            });
        }

        // This is the control for the Test button
        b0.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String url = buildUrl(comp1, freeLabelTextFieldPairs);
                JOptionPane.showMessageDialog(tg, url, TITLE, JOptionPane.INFORMATION_MESSAGE);
            }
        });

        // This is the control for the Set URL button
        b1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                String url = buildUrl(comp1, freeLabelTextFieldPairs);
                endpointTestDialog.setEndpointURL(url);
                b2.doClick();
            }
        });

        // This is the control for the Exit-implement button
        b2.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                endpointTestDialog.setEnabled(true);
                tg.dispose();
            }
        });

        // This is the control for the Clear button
        b3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
               for (int i = 0; i < NUM_PARAMS; i++) {
                   freeLabelTextFieldPairs[i].clearTextField();
                   enableAllPassButtons(true);
                   enableAllUserButtons(true);
                   if (i > 0) {
                       freeUserButtons[i].setVisible(false);
                       freePassButtons[i].setVisible(false);
                   } else {
                       freeUserButtons[i].setVisible(true);
                       freePassButtons[i].setVisible(true);
                   }
               }
               comp1.clearAndFocus();
            }
        });

        p1.add(b0);
        p1.add(b1);
        p1.add(b2);
        p1.add(b3);
        p1.add(comp0);
        p1.add(comp1.getPanel());
        for (int i = 0; i < 4; i++) {
            p1.add(freeLabelTextFieldPairs[i].getPanel());
            p1.add(freeUserButtons[i]);
            p1.add(freePassButtons[i]);
        }
        p1.add(l0);
        this.add(p1);
    }

    private void manageUserPassButtons(int index) {
        freeUserButtons[index].setVisible(false);
        freePassButtons[index].setVisible(false);
        if (freeUserButtons[index + 1].isEnabled()) {
            freeUserButtons[index + 1].setVisible(true);
        }
        if (freePassButtons[index + 1].isEnabled()) {
            freePassButtons[index + 1].setVisible(true);
        }
    }

    private String buildUrl(FreeLabelTextFieldPair comp1, FreeLabelTextFieldPair[] freeLabelTextFieldPairs) {
        String url = comp1.getText();
        for (int i = 0; i < NUM_PARAMS; i++) {
            if (!StringUtils.isEmpty(freeLabelTextFieldPairs[i].getText())) {
                url = url + "/" + freeLabelTextFieldPairs[i].getText();
            } else {
                break;
            }
        }
        return url;
    }

    private void enableAllUserButtons(boolean flag) {
        for (int i = 0; i < NUM_PARAMS; i++) {
            freeUserButtons[i].setEnabled(flag);
        }
    }

    private void enableAllPassButtons(boolean flag) {
        for (int i = 0; i < NUM_PARAMS; i++) {
            freePassButtons[i].setEnabled(flag);
        }
    }
}
