/* This file is auto-generated by the ScriptDirectedGui program.                  */
/* Please do not modify directly as the code cannot then be guaranteed to operate */
/* correctly. However, please feel free to copy the source into a project.        */

package com.ptconsultancy.createdgui;

import static com.ptconsultancy.constants.FileSystemConstants.EXCLUSION_FILE;
import static com.ptconsultancy.constants.FileSystemConstants.LOCAL_TEST_ENV;
import static com.ptconsultancy.constants.ServiceAdminConstants.MAIN_HEADING;
import static com.ptconsultancy.constants.ServiceAdminConstants.STANDARD_DROPDOWN_SELECT;
import static com.ptconsultancy.constants.ServiceAdminConstants.TRUE;

import com.ptconsultancy.domain.guicomponents.FreeButton;
import com.ptconsultancy.domain.guicomponents.FreeLabel;
import com.ptconsultancy.domain.guicomponents.FreeLabelComboBoxPair;
import com.ptconsultancy.domain.utilities.FileUtilities;
import com.ptconsultancy.helpers.NewServiceHelper;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class DeleteServicesDialog extends NewServiceHelper {

    private static final String SUB_HEADING = "Delete Service";
    private static final String TITLE = MAIN_HEADING + " - " + SUB_HEADING;
    private static final int FRAME_X_SIZE = 550;
    private static final int FRAME_Y_SIZE = 250;
    private Color col = new Color(230, 255, 255);

    private DeleteServicesDialog tg = this;

    private MainDialog mainDialog;

    public DeleteServicesDialog(MainDialog mainDialog) {
        this.mainDialog = mainDialog;
        mainDialog.setEnabled(false);

        this.setTitle(TITLE);
        this.setSize(FRAME_X_SIZE, FRAME_Y_SIZE);

        JPanel p1 = new JPanel();
        p1.setLayout(null);
        p1.setBackground(col);

        FreeLabel l0 = new FreeLabel(MAIN_HEADING, 30, 30, 500, 30, new Font("", Font.BOLD + Font.ITALIC, 20));

        FreeButton b0 = new FreeButton(FreeButton.OK, 180, 150, 80);

        FreeButton b1 = new FreeButton(FreeButton.CANCEL, 290, 150, 80);

        String exclusions = "";
        try {
            exclusions = FileUtilities.writeFileToString(EXCLUSION_FILE);
        } catch (IOException e) {
            e.printStackTrace();
        }

        ArrayList<String> items0 = new ArrayList<String>();
        items0.add(STANDARD_DROPDOWN_SELECT);
        File targetDir = new File(LOCAL_TEST_ENV);
        File[] allFiles = targetDir.listFiles();
        for (File service : allFiles) {
            if (service.isDirectory() && !exclusions.contains(service.getName())) {
                items0.add(service.getName());
            }
        }
        FreeLabelComboBoxPair comp0 = new FreeLabelComboBoxPair(col, "Please select service to delete:", 30, 90, 240, items0);

        // This is the control for the OK button
        b0.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (!comp0.isFirstItemSelected()) {
                    int res = JOptionPane.showConfirmDialog(tg, "Are you sure you wish to delete the service " + comp0.getSelectedItem() + "?",
                        TITLE, JOptionPane.YES_NO_CANCEL_OPTION);
                    if (res == 0) {
                        System.out.println("The service will be deleted here");
                        try {
                            deleteServiceFromSource(comp0.getSelectedItem());
                            deleteServiceFromJenkinsTarget(comp0.getSelectedItem());
                        } catch (IOException e1) {
                            e1.printStackTrace();
                        }
                    }
                    b1.doClick();
                } else {
                    JOptionPane.showMessageDialog(tg, "No service selected - please select a service before continuing",
                        TITLE, JOptionPane.INFORMATION_MESSAGE);
                }
            }
        });

        // This is the control for the Cancel-implement button
        b1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                mainDialog.setEnabled(TRUE);
                tg.dispose();
            }
        });

        p1.add(b0);
        p1.add(b1);
        p1.add(comp0.getPanel());
        p1.add(l0);
        this.add(p1);
    }
}
