/* This file is auto-generated by the ScriptDirectedGui program.                  */
/* Please do not modify directly as the code cannot then be guaranteed to operate */
/* correctly. However, please feel free to copy the source into a project.        */

package com.ptconsultancy.createdgui;

import static com.ptconsultancy.constants.FileSystemConstants.ROOT_PATH;
import static com.ptconsultancy.constants.ServiceAdminConstants.MAIN_HEADING;

import com.ptconsultancy.domain.guicomponents.FreeButton;
import com.ptconsultancy.domain.guicomponents.FreeLabel;
import com.ptconsultancy.domain.guicomponents.FreeTextArea;
import com.ptconsultancy.domain.utilities.FileUtilities;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.IOException;
import javax.swing.JFrame;
import javax.swing.JPanel;

public class HelpDialog extends JFrame {



    private static final String TITLE = MAIN_HEADING;
    private static final int FRAME_X_SIZE = 1000;
    private static final int FRAME_Y_SIZE = 900;
    private Color col = new Color(235, 255, 255);

    private JPanel p1 = new JPanel();

    private HelpDialog tg = this;

    MainDialog mainDialog;

    FreeButton b0 = new FreeButton(FreeButton.CLOSE, 460, 800, 80);
    FreeTextArea comp0 = new FreeTextArea(col, "Help details:", 30, 90, 200, 935, 620, false);

    public HelpDialog(MainDialog mainDialog) {

        this.mainDialog = mainDialog;
        mainDialog.setEnabled(false);

        this.setTitle(TITLE);
        this.setSize(FRAME_X_SIZE, FRAME_Y_SIZE);

        p1.setLayout(null);
        p1.setBackground(col);

        FreeLabel l0 = new FreeLabel(MAIN_HEADING, 30, 30, 500, 30, new Font("", Font.BOLD + Font.ITALIC, 20));

        // This is the control for the Exit-implement button
        b0.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                mainDialog.setEnabled(true);
                tg.dispose();
            }
        });

        String helpText = "";
        try {
            helpText = FileUtilities.writeFileToString(ROOT_PATH + "help.txt");
        } catch (IOException e) {
            helpText = "Help text file failed to load";
        }

        comp0.setText(helpText);

        p1.add(b0);
        p1.add(comp0.getPanel());
        p1.add(l0);

        this.add(p1);
    }
}
