/* This file is auto-generated by the ScriptDirectedGui program.         */
/* Please do not modify directly, but feel free to copy into a project   */

package com.ptconsultancy.createdgui;

import static com.ptconsultancy.constants.ServiceAdminConstants.MAIN_HEADING;
import static com.ptconsultancy.constants.ServiceAdminConstants.TRUE;

import com.ptconsultancy.domain.guicomponents.FreeButton;
import com.ptconsultancy.domain.guicomponents.FreeCheckBox;
import com.ptconsultancy.domain.guicomponents.FreeLabel;
import com.ptconsultancy.domain.guicomponents.FreeLabelTextFieldPair;
import com.ptconsultancy.domain.utilities.FileUtilities;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.http.client.support.BasicAuthorizationInterceptor;
import org.springframework.web.client.RestClientException;
import org.springframework.web.client.RestTemplate;

public class NewWebServiceDialog extends JFrame {

    private static final String PROJECT_PATH = "C:/GradleTutorials";

    private static final String SUB_HEADING = " - Create New Frontend Web Service";
    private static final String TITLE = MAIN_HEADING + SUB_HEADING;

    private static final int FRAME_X_SIZE = 550;
    private static final int FRAME_Y_SIZE = 350;
    private Color col = new Color(230, 255, 255);

    private NewWebServiceDialog tg = this;
    private MainDialog mainDialog;

    private String mode;

    public NewWebServiceDialog(MainDialog mainDialog) {

        this.mainDialog = mainDialog;
        this.mainDialog.setEnabled(false);

        this.setTitle(TITLE);
        this.setSize(FRAME_X_SIZE, FRAME_Y_SIZE);

        JPanel p1 = new JPanel();
        p1.setLayout(null);
        p1.setBackground(col);

        File file = new File(PROJECT_PATH);
        if (!file.exists()) {
            file.mkdir();
        }

        FreeLabel l0 = new FreeLabel(MAIN_HEADING, 30, 30, 500, 30, new Font("", Font.BOLD + Font.ITALIC, 20));

        FreeButton b0 = new FreeButton(FreeButton.OK, 180, 250, 80);

        FreeButton b1 = new FreeButton(FreeButton.CANCEL, 290, 250, 80);

        FreeLabelTextFieldPair comp0 = new FreeLabelTextFieldPair(col, "Please enter the new service name:", 30, 90, 240);

        FreeLabelTextFieldPair comp1 = new FreeLabelTextFieldPair(col, "Please select a port for the new service:", 30, 140, 240);

        FreeCheckBox cb1 = new FreeCheckBox(col, "Check if this new service will be built in Jenkins", 30, 190, 300, 20);

        comp0.getTextField().addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                b0.doClick();
            }
        });

        comp1.getTextField().addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                b0.doClick();
            }
        });

        // This is the control for the OK button
        b0.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {

                boolean isPortInteger = true;
                // Check that port number is an integer
                try {
                    if (!comp1.empty()) {
                        int portNum = Integer.parseInt(comp1.getText());
                    }
                } catch (NumberFormatException nfe) {
                    isPortInteger = false;
                }

                String filename = "C:/GradleTutorials/ServicesAdminManager/gitinit.bat";
                if (!comp0.empty() && isPortInteger) {
                    File targDir = new File(PROJECT_PATH + "/" + comp0.getText());
                    if (targDir.mkdir()) {
                        createNewServiceFiles(targDir);

                        // Update build.gradle file with new details
                        updateBuildGradleFile(comp0);

                        // Update application.properties to hold chosen server port
                        if (!comp1.empty()) {
                            updateApplicationPropsFile(comp0, comp1);
                        }

                        // Update banner.txt file
                        updateBannerFile(comp0);

                        // Update messages file
                        updateMessagesFile(comp0);

                        // Remove .git directory to break link to remote origin
                        removeGitDependency(comp0);
                        // Create new Git initialisation
                        if (cb1.isSelected()) {
                            try {
                                FileUtilities.writeStringToFile(filename, "cd\\\n");
                                FileUtilities.appendStringToFile(filename, "cd C:\\GradleTutorials\\" + comp0.getText() + "\n\n");
                                FileUtilities.appendStringToFile(filename,"git init\n");
                                FileUtilities.appendStringToFile(filename,"git add *\n");
                                FileUtilities.appendStringToFile(filename,"git commit -m \"First Commit\"\n");
//                                FileUtilities.appendStringToFile(filename, "git remote add origin https://github.com/Petert3660/" + comp0.getText() + ".git\n");
//                                FileUtilities.appendStringToFile(filename, "git push -u origin master");
                                Process process = Runtime.getRuntime().exec("C:\\GradleTutorials\\ServicesAdminManager\\gitinit.bat");

                                JOptionPane.showMessageDialog(tg,
                                    "IMPORTANT! About to set up new Jenkins Project - First you should make sure the new repository, "
                                        + comp0.getText() + ".git is published to the remoe origin. Do this NOW before proceeding",
                                    TITLE, JOptionPane.INFORMATION_MESSAGE);

                                String jenkinsFile = "C://GradleTutorials/ServicesAdminManager/JenkinsModelConfig.xml";
                                String xml = FileUtilities.writeFileToString(jenkinsFile);
                                xml = xml.replace("<Project Name Here>", comp0.getText());

                                HttpHeaders httpHeaders = new HttpHeaders();
                                httpHeaders.setContentType(MediaType.APPLICATION_XML);
                                HttpEntity<String> request = new HttpEntity<>(xml, httpHeaders);
                                RestTemplate restTemplate = new RestTemplate();
                                restTemplate.getInterceptors().add(new BasicAuthorizationInterceptor("petert3660", "2905e6a2fd0251f555bd90c055e0ff18"));
                                String endpoint = "http://localhost:8080/createItem?name=" + comp0.getText();
                                URI uri = new URI(endpoint);
                                try {
                                    ResponseEntity<String> responseEntity = restTemplate.postForEntity(uri, request, String.class);
                                } catch (RestClientException rce) {
                                    System.out.println("In REST exception catch");
                                    rce.printStackTrace();
                                }
                            } catch (IOException e1) {
                                e1.printStackTrace();
                            } catch (URISyntaxException e1) {
                                e1.printStackTrace();
                            }
                        }

                        JOptionPane.showMessageDialog(tg,
                            "Service: " + comp0.getText() + " has been successfully created",
                            TITLE, JOptionPane.INFORMATION_MESSAGE);

                        File file = new File(filename);
                        if (file.exists()) {
                            file.delete();
                        }

                        b1.doClick();
                    } else {
                        JOptionPane.showMessageDialog(tg, "Unable to create service: " + comp0.getText()
                                + " , there may already be a service with this name",
                            TITLE, JOptionPane.INFORMATION_MESSAGE);
                        comp0.clearAndFocus();
                    }
                } else {
                    if (comp0.empty()) {
                        JOptionPane.showMessageDialog(tg, "The name of the new service cannot be empty - please choose a name",
                            TITLE, JOptionPane.INFORMATION_MESSAGE);
                        comp0.clearAndFocus();
                    }
                    if (!isPortInteger) {
                        JOptionPane.showMessageDialog(tg, "The new service port must be an integer - please re-enter or leav empty for default value",
                            TITLE, JOptionPane.INFORMATION_MESSAGE);
                        comp1.clearAndFocus();
                    }
                }
            }
        });

        // This is the control for the Cancel-implement button
        b1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                mainDialog.setEnabled(TRUE);
                tg.dispose();
            }
        });

        p1.add(b0);
        p1.add(b1);
        p1.add(comp0.getPanel());
        p1.add(comp1.getPanel());
        p1.add(cb1);
        p1.add(l0);
        this.add(p1);
    }

    private void createNewServiceFiles(File targDir) {
        File srcDir = new File("C:/GradleTutorials/SkeletonSpringBootWebProject");
        final String SETTINGS_GRADLE = "/settings.gradle";
        final String RUN_BAT = "/run.bat";
        final String SETUP_BAT = "/setup.bat";
        try {
            FileUtilities.copyAllFilesFromSrcDirToTargetDir(srcDir.getAbsolutePath(),
                targDir.getAbsolutePath());
            FileUtilities.deleteFile(targDir.getAbsolutePath() + SETTINGS_GRADLE);
            FileUtilities.writeStringToFile(
                targDir.getAbsolutePath() + SETTINGS_GRADLE,
                "rootProject.name = '" + targDir.getName() + "'\n");
            FileUtilities.deleteFile(targDir.getAbsolutePath() + RUN_BAT);
            FileUtilities.writeStringToFile(targDir.getAbsolutePath() + RUN_BAT,
                "cd build/libs\n\n");
            FileUtilities.appendStringToFile(targDir.getAbsolutePath() + RUN_BAT,
                "java -jar " + targDir.getName() + ".jar\n");
            FileUtilities.writeStringToFile(targDir.getAbsolutePath() + SETUP_BAT,
                "echo off\n\n");
            FileUtilities.appendStringToFile(targDir.getAbsolutePath() + SETUP_BAT,
                "set myDirName = \".\\build\\libs\"\n\n");
            FileUtilities.appendStringToFile(targDir.getAbsolutePath() + SETUP_BAT,
                "if exist myDirName (\n");
            FileUtilities.appendStringToFile(targDir.getAbsolutePath() + SETUP_BAT,
                "    cd build\\libs\n");
            FileUtilities.appendStringToFile(targDir.getAbsolutePath() + SETUP_BAT,
                "    del *.*\n");
            FileUtilities.appendStringToFile(targDir.getAbsolutePath() + SETUP_BAT,
                "    cd ..\\..\n");
            FileUtilities.appendStringToFile(targDir.getAbsolutePath() + SETUP_BAT,
                ")\n\n");
            FileUtilities.appendStringToFile(targDir.getAbsolutePath() + SETUP_BAT,
                "call gradlew clean build\n");
            FileUtilities.appendStringToFile(targDir.getAbsolutePath() + SETUP_BAT,
                "call run\n");
            FileUtilities.appendStringToFile(targDir.getAbsolutePath() + SETUP_BAT,
                "cd ..\\..\n");
        } catch (IOException e1) {
            e1.printStackTrace();
        }
    }

    private void removeGitDependency(FreeLabelTextFieldPair comp0) {
        File srcDir;
        final String NEW_TARGET = PROJECT_PATH + "/" + comp0.getText();
        srcDir = new File(NEW_TARGET);
        File[] files = srcDir.listFiles();

        for (File targfile : files) {
            if (targfile.getName().equals(".git") && targfile.isDirectory()) {
                try {
                    FileUtilities.deleteDirectory(targfile);
                } catch (IOException e1) {
                    e1.printStackTrace();
                }
            }

            if (targfile.getAbsolutePath().contains(".iml")) {
                FileUtilities.deleteFile(targfile.getAbsolutePath());
            }
        }
    }

    private void updateBuildGradleFile(FreeLabelTextFieldPair comp0) {
        final String BUILD_GRADLE_FILE = PROJECT_PATH + "/" + comp0.getText() + "/build.gradle";
        File buildFile = new File(BUILD_GRADLE_FILE);

        try {
            String allGradleContents = FileUtilities.writeFileToString(BUILD_GRADLE_FILE);
            if (buildFile.exists()) {
                buildFile.delete();
            }
            allGradleContents = allGradleContents.replace("projectName = \"SkeletonSpringBootWebProject\"",
                "projectName = \"" + comp0.getText() + "\"");
            allGradleContents = allGradleContents.replace("projectTitle = \"Skeleton Spring Boot Web Project\"",
                "projectTitle = \"" + comp0.getText() + "\"");
            FileUtilities.writeStringToFile(BUILD_GRADLE_FILE, allGradleContents);
        } catch (IOException e1) {
            e1.printStackTrace();
        }
    }

    private void updateApplicationPropsFile(FreeLabelTextFieldPair comp0, FreeLabelTextFieldPair comp1) {
        final String APP_PROPS_FILE = PROJECT_PATH + "/" + comp0.getText() + "/src/main/resources/application.properties";
        File appPropFile = new File(APP_PROPS_FILE);

        try {
            String allAppPropContents = FileUtilities.writeFileToString(APP_PROPS_FILE);
            if (appPropFile.exists()) {
                appPropFile.delete();
            }
            allAppPropContents = allAppPropContents.replace("server.port=8180",
                "server.port=" + comp1.getText());
            FileUtilities.writeStringToFile(APP_PROPS_FILE, allAppPropContents);
        } catch (IOException e1) {
            e1.printStackTrace();
        }
    }

    private void updateBannerFile(FreeLabelTextFieldPair comp0) {
        final String BANNER_FILE = PROJECT_PATH + "/" + comp0.getText() + "/src/main/resources/banner.txt";
        File bannerFile = new File(BANNER_FILE);

        try {
            String allBannerContents = FileUtilities.writeFileToString(BANNER_FILE);
            if (bannerFile.exists()) {
                bannerFile.delete();
            }
            allBannerContents = allBannerContents.replace("Skeleton Spring Boot Web Project",
                comp0.getText());
            FileUtilities.writeStringToFile(BANNER_FILE, allBannerContents);
        } catch (IOException e1) {
            e1.printStackTrace();
        }
    }

    private void updateMessagesFile(FreeLabelTextFieldPair comp0) {
        final String MESSAGES_FILE = PROJECT_PATH + "/" + comp0.getText() + "/src/main/resources/messages.properties";
        File bannerFile = new File(MESSAGES_FILE);

        try {
            String allMessagesContents = FileUtilities.writeFileToString(MESSAGES_FILE);
            if (bannerFile.exists()) {
                bannerFile.delete();
            }
            allMessagesContents = allMessagesContents.replace("Skeleton Spring Boot Web Project",
                comp0.getText());
            FileUtilities.writeStringToFile(MESSAGES_FILE, allMessagesContents);
        } catch (IOException e1) {
            e1.printStackTrace();
        }
    }
}
