/* This file is auto-generated by the ScriptDirectedGui program.         */
/* Please do not modify directly, but feel free to copy into a project   */

package com.ptconsultancy.createdgui;

import static com.ptconsultancy.constants.FileSystemConstants.BANNER_FILE;
import static com.ptconsultancy.constants.FileSystemConstants.LOCAL_SRC;
import static com.ptconsultancy.constants.FileSystemConstants.MESSAGE_FILE;
import static com.ptconsultancy.constants.InformationMessages.SERVICE_NAME_NOT_EMPTY;
import static com.ptconsultancy.constants.InformationMessages.SERVICE_PORT_INTEGER;
import static com.ptconsultancy.constants.ServiceAdminConstants.MAIN_HEADING;
import static com.ptconsultancy.constants.ServiceAdminConstants.TRUE;

import com.ptconsultancy.constants.InformationMessages;
import com.ptconsultancy.domain.guicomponents.FreeButton;
import com.ptconsultancy.domain.guicomponents.FreeCheckBox;
import com.ptconsultancy.domain.guicomponents.FreeLabel;
import com.ptconsultancy.domain.guicomponents.FreeLabelTextFieldPair;
import com.ptconsultancy.domain.utilities.CommonUtils;
import com.ptconsultancy.domain.utilities.FileUtilities;
import com.ptconsultancy.helpers.NewServiceHelper;
import java.awt.Color;
import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.io.IOException;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.core.env.Environment;

public class NewWebServiceDialog extends NewServiceHelper {

    private static final String PROJECT_TITLE = "Skeleton Spring Boot Web Project";

    private static final String TITLE = "Create New Frontend Web Service";
    private static final int FRAME_X_SIZE = 550;
    private static final int FRAME_Y_SIZE = 350;
    private Color col = new Color(230, 255, 255);

    private NewWebServiceDialog tg = this;
    private MainDialog mainDialog;

    private Environment env;
    private String mode;

    @Autowired
    public NewWebServiceDialog(MainDialog mainDialog, Environment env) {

        this.mainDialog = mainDialog;
        this.env = env;
        setEnv(this.env);
        this.mainDialog.setEnabled(false);

        this.setTitle(TITLE);
        this.setSize(FRAME_X_SIZE, FRAME_Y_SIZE);

        JPanel p1 = new JPanel();
        p1.setLayout(null);
        p1.setBackground(col);

        File file = new File(LOCAL_SRC);
        if (!file.exists()) {
            file.mkdir();
        }

        FreeLabel l0 = new FreeLabel(MAIN_HEADING, 30, 30, 500, 30, new Font("", Font.BOLD + Font.ITALIC, 20));

        FreeButton b0 = new FreeButton(FreeButton.OK, 180, 250, 80);

        FreeButton b1 = new FreeButton(FreeButton.CANCEL, 290, 250, 80);

        FreeLabelTextFieldPair comp0 = new FreeLabelTextFieldPair(col, "Please enter the new service name:", 30, 90, 240);

        FreeLabelTextFieldPair comp1 = new FreeLabelTextFieldPair(col, "Please select a port for the new service:", 30, 140, 240);

        FreeCheckBox cb1 = new FreeCheckBox(col, "Check if this new service will be built in Jenkins", 30, 190, 300, 20);

        comp0.getTextField().addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                b0.doClick();
            }
        });

        comp1.getTextField().addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                b0.doClick();
            }
        });

        // This is the control for the OK button
        b0.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {

                boolean isPortInteger = CommonUtils.isNumberAnInteger(comp1.getText());

                if (!comp0.empty() && isPortInteger) {
                    File targDir = new File(LOCAL_SRC + "/" + comp0.getText());
                    if (targDir.mkdir()) {
                        createNewServiceFiles(targDir,  LOCAL_SRC + "/SkeletonSpringBootWebProject");

                        // Update build.gradle file with new details
                        updateBuildGradleFile(comp0, PROJECT_TITLE);

                        // Update application.properties to hold chosen server port
                        if (!comp1.empty()) {
                            updateApplicationPropsFile(comp0, comp1);
                        }

                        // Update banner.txt file
                        updateFile(comp0, BANNER_FILE);

                        // Update messages file
                        updateFile(comp0, MESSAGE_FILE);

                        // Remove .git directory to break link to remote origin
                        removeGitDependency(comp0);
                        // Create new Git initialisation
                        if (cb1.isSelected()) {
                            updateGitAndJenkins(comp0, tg, TITLE);
                        }

                        JOptionPane.showMessageDialog(tg,
                            InformationMessages.serviceSuccessfullyAdded(comp0.getText()), TITLE, JOptionPane.INFORMATION_MESSAGE);

                        b1.doClick();
                    } else {
                        JOptionPane.showMessageDialog(tg, InformationMessages.getUnable("service", comp0.getText()), TITLE, JOptionPane.INFORMATION_MESSAGE);
                        comp0.clearAndFocus();
                    }
                } else {
                    if (comp0.empty()) {
                        JOptionPane.showMessageDialog(tg, SERVICE_NAME_NOT_EMPTY, TITLE, JOptionPane.INFORMATION_MESSAGE);
                        comp0.clearAndFocus();
                    }
                    if (!isPortInteger) {
                        JOptionPane.showMessageDialog(tg, SERVICE_PORT_INTEGER, TITLE, JOptionPane.INFORMATION_MESSAGE);
                        comp1.clearAndFocus();
                    }
                }
            }
        });

        // This is the control for the Cancel-implement button
        b1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                mainDialog.setEnabled(TRUE);
                tg.dispose();
            }
        });

        p1.add(b0);
        p1.add(b1);
        p1.add(comp0.getPanel());
        p1.add(comp1.getPanel());
        p1.add(cb1);
        p1.add(l0);
        this.add(p1);
    }

    private void updateApplicationPropsFile(FreeLabelTextFieldPair comp0, FreeLabelTextFieldPair comp1) {
        final String APP_PROPS_FILE = LOCAL_SRC + "/" + comp0.getText() + "/src/main/resources/application.properties";
        File appPropFile = new File(APP_PROPS_FILE);

        try {
            String allAppPropContents = FileUtilities.writeFileToString(APP_PROPS_FILE);
            if (appPropFile.exists()) {
                appPropFile.delete();
            }
            allAppPropContents = allAppPropContents.replace("server.port=8180",
                "server.port=" + comp1.getText());
            FileUtilities.writeStringToFile(APP_PROPS_FILE, allAppPropContents);
        } catch (IOException e1) {
            e1.printStackTrace();
        }
    }

    private void updateFile(FreeLabelTextFieldPair comp0, String fileToUpdate) {
        final String FILE = LOCAL_SRC + "/" + comp0.getText() + fileToUpdate;
        File file = new File(FILE);

        try {
            String allContents = FileUtilities.writeFileToString(FILE);
            if (file.exists()) {
                file.delete();
            }
            allContents = allContents.replace(PROJECT_TITLE,
                comp0.getText());
            FileUtilities.writeStringToFile(FILE, allContents);
        } catch (IOException e1) {
            e1.printStackTrace();
        }
    }
}
